# Development Setup.
# Uses the latest commit of the `master` branch to run each service.
# Start individual services using the following command::
#
#   docker-compose up <service_1> <service_2> [..]
#
# Add the `-d` flag to daemonize the container.
#
# Updating the images is as easy as this:
#
#   docker-compose pull && docker-compose restart
#
# ..Note::
#
#   The above commands assume you're already in the directory where
#   where this docker-compose file is located.
version: '3.4'

x-defaults: &defaults
  image: raidennetwork/raiden-services:latest

services:
  pfs-ropsten:
    << : *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-ropsten.services-dev.raiden.network"

  pfs-rinkeby:
    << : *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-rinkeby.services-dev.raiden.network"

  pfs-goerli:
    <<: *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-goerli.services-dev.raiden.network"

  pfs-ropsten-with-fee:
    << : *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-ropsten-with-fee.services-dev.raiden.network"

  pfs-rinkeby-with-fee:
    << : *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-rinkeby-with-fee.services-dev.raiden.network"

  pfs-goerli-with-fee:
    <<: *defaults
    labels:
      - "traefik.frontend.rule=Host: pfs-goerli-with-fee.services-dev.raiden.network"

  ms-ropsten:
    << : *defaults

  ms-rinkeby:
    << : *defaults

  ms-goerli:
    <<: *defaults

  msrc-ropsten:
    << : *defaults

  msrc-rinkeby:
    << : *defaults

  msrc-goerli:
    <<: *defaults

  registration-goerli:
    <<: *defaults
      - RDN_REGISTRY_SERVICE_URL=https://pfs-goerli-with-fee.services-dev.raiden.network

  builder:
    environment:
      - HOSTNAME=services-dev
    labels:
      - "traefik.frontend.rule=Host: services-dev.raiden.network"
